name: Java Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Укажите здесь желаемую дистрибуцию JDK

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Find test files
        run: |
          echo "Searching for test files in src directory..."
          find ./src -type f -name "*.java" > tests.txt
          echo "Found test files:"
          cat tests.txt # Для проверки, что файлы найдены