name: Java Tests

on:
  pull_request:

jobs:
  build:
    uses: yandex-praktikum/java-kanban/.github/workflows/api-tests.yml@ci

  find-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find test files
        run: |
          find ./src/test -type f -name "*.java" > tests.txt
          cat tests.txt 